# Generated by Django 4.2.4 on 2023-09-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('url', models.TextField()),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
                ('sqm_price', models.IntegerField()),
                ('sqm_size', models.TextField()),
                ('monthly_fee', models.IntegerField()),
                ('room_count', models.TextField()),
                ('image_url', models.TextField()),
                ('hemnet_listing_id', models.IntegerField()),
                ('date_published', models.DateTimeField()),
                ('location_id', models.IntegerField()),
                ('balcony', models.BooleanField()),
                ('patio', models.BooleanField()),
                ('floor', models.TextField()),
                ('elevator', models.TextField()),
            ],
        ),
    ]
