# Generated by Django 4.2.4 on 2023-09-03 19:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(default=api.models.generate_unique_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
